// <auto-generated />
using System;
using ConstructionSiteReportingSystem.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConstructionSiteReportingSystem.Infrastructure.Migrations
{
    [DbContext(typeof(ConstructionSiteDbContext))]
    [Migration("20240903141029_IsApprovedColumnsAddedToTables")]
    partial class IsApprovedColumnsAddedToTables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ConstructionSiteReportingSystem.Infrastructure.Data.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "32f9a0f0-4d62-4573-96e3-fbb7ad7f321f",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "30f87965-b478-471b-a9af-7ba27a5afb65",
                            Email = "test@mail.com",
                            EmailConfirmed = false,
                            FirstName = "Konstantin",
                            LastName = "Georgiev",
                            LockoutEnabled = false,
                            MiddleName = "Kirilov",
                            NormalizedEmail = "TEST@MAIL.COM",
                            NormalizedUserName = "TEST@MAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEHQHFTo/ohCA7rMS/yy6JgL4z0X6ozHg6fq+487ahcxmQQAnGMnWRKkqjKl8z/umkw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "ba2517ae-290e-4fc6-9370-618348f420e1",
                            TwoFactorEnabled = false,
                            UserName = "test@mail.com"
                        },
                        new
                        {
                            Id = "a615552b-5981-4730-be32-12c087492aef",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "1a24add4-026f-4b41-8fbe-372d9e6459da",
                            Email = "guest@mail.com",
                            EmailConfirmed = false,
                            FirstName = "Ivan",
                            LastName = "Petrov",
                            LockoutEnabled = false,
                            MiddleName = "Metodiev",
                            NormalizedEmail = "GUEST@MAIL.COM",
                            NormalizedUserName = "GUEST@MAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEJe6LKAGgS5+8DyUNHlSJN/XEGuepk+PSNlbaFlbziSeXeKwWSwoAuBKZSZYgzyk4Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "6d77187c-9d4b-47f4-a8ff-e5cefe3e8746",
                            TwoFactorEnabled = false,
                            UserName = "guest@mail.com"
                        },
                        new
                        {
                            Id = "51d6e97b-9c12-4832-95e1-c0dfa1715ad9",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "990475c9-4def-4f55-af22-dbf319c1c188",
                            Email = "admin@mail.com",
                            EmailConfirmed = false,
                            FirstName = "Anton",
                            LastName = "Kovadzhiev",
                            LockoutEnabled = false,
                            MiddleName = "Naidenov",
                            NormalizedEmail = "ADMIN@MAIL.COM",
                            NormalizedUserName = "ADMIN@MAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEFULviZPa/0Zul35W+Dz1uwckdH3+6AlHBbzP96h+FFQjrVsiVR8C0gJzuanLRSarg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "9df45db0-b489-4f74-bb1d-17d261c2c60d",
                            TwoFactorEnabled = false,
                            UserName = "admin@mail.com"
                        });
                });

            modelBuilder.Entity("ConstructionSiteReportingSystem.Infrastructure.Data.Models.Contractor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Construction contractor identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit")
                        .HasComment("Is construction contractor approved by the administrator");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Construction contractor name");

                    b.HasKey("Id");

                    b.ToTable("Contractors");

                    b.HasComment("Construction contractor");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsApproved = true,
                            IsDeleted = false,
                            Name = "GBS Build"
                        },
                        new
                        {
                            Id = 2,
                            IsApproved = true,
                            IsDeleted = false,
                            Name = "M Constructions"
                        },
                        new
                        {
                            Id = 3,
                            IsApproved = true,
                            IsDeleted = false,
                            Name = "Quality Plumbing"
                        },
                        new
                        {
                            Id = 4,
                            IsApproved = true,
                            IsDeleted = false,
                            Name = "Pavement Systems"
                        },
                        new
                        {
                            Id = 5,
                            IsApproved = true,
                            IsDeleted = false,
                            Name = "NewSteel LTD"
                        });
                });

            modelBuilder.Entity("ConstructionSiteReportingSystem.Infrastructure.Data.Models.Site", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Construction site identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTime>("FinishDate")
                        .HasColumnType("datetime2")
                        .HasComment("Construction site finish date");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Construction site image URL");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Construction site name");

                    b.HasKey("Id");

                    b.ToTable("Sites");

                    b.HasComment("Construction site");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FinishDate = new DateTime(2027, 9, 3, 17, 10, 28, 518, DateTimeKind.Local).AddTicks(5917),
                            ImageUrl = "https://images.pexels.com/photos/220885/pexels-photo-220885.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
                            IsDeleted = false,
                            Name = "Plant construction for production of electric bicycles MaxCompany"
                        },
                        new
                        {
                            Id = 2,
                            FinishDate = new DateTime(2029, 9, 3, 17, 10, 28, 518, DateTimeKind.Local).AddTicks(5957),
                            ImageUrl = "https://images.pexels.com/photos/2833686/pexels-photo-2833686.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
                            IsDeleted = false,
                            Name = "Construction of streets in Plovdiv Municipality"
                        },
                        new
                        {
                            Id = 3,
                            FinishDate = new DateTime(2026, 9, 3, 17, 10, 28, 518, DateTimeKind.Local).AddTicks(5961),
                            ImageUrl = "https://images.pexels.com/photos/236698/pexels-photo-236698.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
                            IsDeleted = false,
                            Name = "Plant construction for cardboard packaging GreenPac"
                        });
                });

            modelBuilder.Entity("ConstructionSiteReportingSystem.Infrastructure.Data.Models.Stage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Construction stage identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit")
                        .HasComment("Is construction stage approved by the administrator");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Construction stage name");

                    b.HasKey("Id");

                    b.ToTable("Stages");

                    b.HasComment("Construction stage");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsApproved = true,
                            IsDeleted = false,
                            Name = "Sitework and foundation"
                        },
                        new
                        {
                            Id = 2,
                            IsApproved = true,
                            IsDeleted = false,
                            Name = "Rough framing"
                        },
                        new
                        {
                            Id = 3,
                            IsApproved = true,
                            IsDeleted = false,
                            Name = "Exterior construction"
                        },
                        new
                        {
                            Id = 4,
                            IsApproved = true,
                            IsDeleted = false,
                            Name = "Mechanical, electrical and plumbing"
                        },
                        new
                        {
                            Id = 5,
                            IsApproved = true,
                            IsDeleted = false,
                            Name = "Finishes and fixtures"
                        });
                });

            modelBuilder.Entity("ConstructionSiteReportingSystem.Infrastructure.Data.Models.Task", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Task identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2")
                        .HasComment("Task creation date");

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasComment("Task creator identifier");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasComment("Task description");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasComment("Task's current status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Task title");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.ToTable("Tasks");

                    b.HasComment("User tasks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOn = new DateTime(2024, 9, 3, 17, 10, 28, 637, DateTimeKind.Local).AddTicks(2678),
                            CreatorId = "32f9a0f0-4d62-4573-96e3-fbb7ad7f321f",
                            Description = "Must order 5m3 concrete class C20/25 with delivery date next Monday",
                            IsDeleted = false,
                            Status = 0,
                            Title = "Order concrete"
                        },
                        new
                        {
                            Id = 2,
                            CreatedOn = new DateTime(2024, 10, 3, 17, 10, 28, 637, DateTimeKind.Local).AddTicks(2684),
                            CreatorId = "32f9a0f0-4d62-4573-96e3-fbb7ad7f321f",
                            Description = "Should start looking through documentation and drawings of upcoming project",
                            IsDeleted = false,
                            Status = 0,
                            Title = "New project documentation"
                        },
                        new
                        {
                            Id = 3,
                            CreatedOn = new DateTime(2024, 8, 29, 17, 10, 28, 637, DateTimeKind.Local).AddTicks(2687),
                            CreatorId = "32f9a0f0-4d62-4573-96e3-fbb7ad7f321f",
                            Description = "Go to weekly site Monday meeting",
                            IsDeleted = false,
                            Status = 2,
                            Title = "Weekly meeting"
                        },
                        new
                        {
                            Id = 4,
                            CreatedOn = new DateTime(2024, 9, 3, 17, 10, 28, 637, DateTimeKind.Local).AddTicks(2689),
                            CreatorId = "32f9a0f0-4d62-4573-96e3-fbb7ad7f321f",
                            Description = "Fill in monthly workers attendance forms and send them to accounting by the end of month",
                            IsDeleted = false,
                            Status = 1,
                            Title = "Monthly workers attendance forms"
                        },
                        new
                        {
                            Id = 5,
                            CreatedOn = new DateTime(2024, 9, 3, 17, 10, 28, 637, DateTimeKind.Local).AddTicks(2692),
                            CreatorId = "a615552b-5981-4730-be32-12c087492aef",
                            Description = "Call engineer supervisor and schedule meeting to discuss construction work progress and difficulties",
                            IsDeleted = false,
                            Status = 0,
                            Title = "Schedule meeting"
                        },
                        new
                        {
                            Id = 6,
                            CreatedOn = new DateTime(2024, 9, 8, 17, 10, 28, 637, DateTimeKind.Local).AddTicks(2695),
                            CreatorId = "a615552b-5981-4730-be32-12c087492aef",
                            Description = "Call Doka representative and order more formwork for site",
                            IsDeleted = false,
                            Status = 0,
                            Title = "Formwork"
                        });
                });

            modelBuilder.Entity("ConstructionSiteReportingSystem.Infrastructure.Data.Models.Unit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Measurement unit identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit")
                        .HasComment("Is measurement unit approved by the administrator");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasComment("Measurement unit type");

                    b.HasKey("Id");

                    b.ToTable("Units");

                    b.HasComment("Measurement unit");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsApproved = true,
                            IsDeleted = false,
                            Type = "ton"
                        },
                        new
                        {
                            Id = 2,
                            IsApproved = true,
                            IsDeleted = false,
                            Type = "kg"
                        },
                        new
                        {
                            Id = 3,
                            IsApproved = true,
                            IsDeleted = false,
                            Type = "cu.m"
                        },
                        new
                        {
                            Id = 4,
                            IsApproved = true,
                            IsDeleted = false,
                            Type = "sq.m"
                        },
                        new
                        {
                            Id = 5,
                            IsApproved = true,
                            IsDeleted = false,
                            Type = "m"
                        },
                        new
                        {
                            Id = 6,
                            IsApproved = true,
                            IsDeleted = false,
                            Type = "piece"
                        },
                        new
                        {
                            Id = 7,
                            IsApproved = true,
                            IsDeleted = false,
                            Type = "piece/m"
                        },
                        new
                        {
                            Id = 8,
                            IsApproved = true,
                            IsDeleted = false,
                            Type = "machine shift"
                        },
                        new
                        {
                            Id = 9,
                            IsApproved = true,
                            IsDeleted = false,
                            Type = "man hours"
                        });
                });

            modelBuilder.Entity("ConstructionSiteReportingSystem.Infrastructure.Data.Models.Work", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Construction and assembly work identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CarryOutDate")
                        .HasColumnType("datetime2")
                        .HasComment("Construction and assembly work carry out date and time");

                    b.Property<int>("ContractorId")
                        .HasColumnType("int")
                        .HasComment("Construction and assembly work contractor identifier");

                    b.Property<decimal>("CostPerUnit")
                        .HasColumnType("decimal(18,2)")
                        .HasComment("Construction and assembly work cost per measurement unit");

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasComment("Construction and assembly work creator identifier");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasComment("Construction and assembly work description");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<double>("Quantity")
                        .HasColumnType("float")
                        .HasComment("Construction and assembly work quantity");

                    b.Property<int>("SiteId")
                        .HasColumnType("int")
                        .HasComment("Construction and assembly work site identifier");

                    b.Property<int>("StageId")
                        .HasColumnType("int")
                        .HasComment("Construction and assembly work stage identifier");

                    b.Property<decimal>("TotalCost")
                        .HasColumnType("decimal(36,2)")
                        .HasComment("Construction and assembly work total cost");

                    b.Property<int>("UnitId")
                        .HasColumnType("int")
                        .HasComment("Construction and assembly work measurement unit identifier");

                    b.Property<int>("WorkTypeId")
                        .HasColumnType("int")
                        .HasComment("Construction and assembly work type identifier");

                    b.HasKey("Id");

                    b.HasIndex("ContractorId");

                    b.HasIndex("CreatorId");

                    b.HasIndex("SiteId");

                    b.HasIndex("StageId");

                    b.HasIndex("UnitId");

                    b.HasIndex("WorkTypeId");

                    b.ToTable("Works");

                    b.HasComment("Construction and assembly work");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CarryOutDate = new DateTime(2024, 9, 3, 17, 10, 28, 612, DateTimeKind.Local).AddTicks(9242),
                            ContractorId = 3,
                            CostPerUnit = 23m,
                            CreatorId = "32f9a0f0-4d62-4573-96e3-fbb7ad7f321f",
                            IsDeleted = false,
                            Quantity = 897.0,
                            SiteId = 1,
                            StageId = 4,
                            TotalCost = 20631m,
                            UnitId = 5,
                            WorkTypeId = 1
                        },
                        new
                        {
                            Id = 2,
                            CarryOutDate = new DateTime(2024, 9, 3, 17, 10, 28, 612, DateTimeKind.Local).AddTicks(9249),
                            ContractorId = 4,
                            CostPerUnit = 42.5m,
                            CreatorId = "32f9a0f0-4d62-4573-96e3-fbb7ad7f321f",
                            IsDeleted = false,
                            Quantity = 120.0,
                            SiteId = 1,
                            StageId = 1,
                            TotalCost = 5100m,
                            UnitId = 3,
                            WorkTypeId = 2
                        },
                        new
                        {
                            Id = 3,
                            CarryOutDate = new DateTime(2024, 9, 2, 17, 10, 28, 612, DateTimeKind.Local).AddTicks(9346),
                            ContractorId = 4,
                            CostPerUnit = 35.5m,
                            CreatorId = "32f9a0f0-4d62-4573-96e3-fbb7ad7f321f",
                            Description = "Entered cost for crushed aggredate material and delivery",
                            IsDeleted = false,
                            Quantity = 150.0,
                            SiteId = 1,
                            StageId = 1,
                            TotalCost = 5325m,
                            UnitId = 3,
                            WorkTypeId = 2
                        },
                        new
                        {
                            Id = 4,
                            CarryOutDate = new DateTime(2024, 9, 2, 17, 10, 28, 612, DateTimeKind.Local).AddTicks(9351),
                            ContractorId = 2,
                            CostPerUnit = 600m,
                            CreatorId = "32f9a0f0-4d62-4573-96e3-fbb7ad7f321f",
                            Description = "Entered cost for crushed aggredate compaction using 11 ton roller",
                            IsDeleted = false,
                            Quantity = 1.0,
                            SiteId = 1,
                            StageId = 1,
                            TotalCost = 600m,
                            UnitId = 8,
                            WorkTypeId = 2
                        },
                        new
                        {
                            Id = 5,
                            CarryOutDate = new DateTime(2024, 9, 1, 17, 10, 28, 612, DateTimeKind.Local).AddTicks(9354),
                            ContractorId = 4,
                            CostPerUnit = 42.5m,
                            CreatorId = "32f9a0f0-4d62-4573-96e3-fbb7ad7f321f",
                            IsDeleted = false,
                            Quantity = 250.0,
                            SiteId = 1,
                            StageId = 1,
                            TotalCost = 10625m,
                            UnitId = 3,
                            WorkTypeId = 2
                        },
                        new
                        {
                            Id = 6,
                            CarryOutDate = new DateTime(2024, 8, 24, 17, 10, 28, 612, DateTimeKind.Local).AddTicks(9368),
                            ContractorId = 4,
                            CostPerUnit = 8m,
                            CreatorId = "32f9a0f0-4d62-4573-96e3-fbb7ad7f321f",
                            Description = "Used combined excavators",
                            IsDeleted = false,
                            Quantity = 150.0,
                            SiteId = 1,
                            StageId = 1,
                            TotalCost = 1200m,
                            UnitId = 3,
                            WorkTypeId = 3
                        },
                        new
                        {
                            Id = 7,
                            CarryOutDate = new DateTime(2024, 8, 22, 17, 10, 28, 612, DateTimeKind.Local).AddTicks(9372),
                            ContractorId = 4,
                            CostPerUnit = 164m,
                            CreatorId = "32f9a0f0-4d62-4573-96e3-fbb7ad7f321f",
                            IsDeleted = false,
                            Quantity = 163.0,
                            SiteId = 1,
                            StageId = 1,
                            TotalCost = 26732m,
                            UnitId = 1,
                            WorkTypeId = 4
                        },
                        new
                        {
                            Id = 8,
                            CarryOutDate = new DateTime(2024, 8, 21, 17, 10, 28, 612, DateTimeKind.Local).AddTicks(9375),
                            ContractorId = 4,
                            CostPerUnit = 164m,
                            CreatorId = "32f9a0f0-4d62-4573-96e3-fbb7ad7f321f",
                            IsDeleted = false,
                            Quantity = 158.0,
                            SiteId = 1,
                            StageId = 1,
                            TotalCost = 25912m,
                            UnitId = 1,
                            WorkTypeId = 4
                        },
                        new
                        {
                            Id = 9,
                            CarryOutDate = new DateTime(2024, 8, 20, 17, 10, 28, 612, DateTimeKind.Local).AddTicks(9378),
                            ContractorId = 4,
                            CostPerUnit = 164m,
                            CreatorId = "32f9a0f0-4d62-4573-96e3-fbb7ad7f321f",
                            IsDeleted = false,
                            Quantity = 75.0,
                            SiteId = 1,
                            StageId = 1,
                            TotalCost = 12300m,
                            UnitId = 1,
                            WorkTypeId = 4
                        },
                        new
                        {
                            Id = 10,
                            CarryOutDate = new DateTime(2024, 8, 19, 17, 10, 28, 612, DateTimeKind.Local).AddTicks(9382),
                            ContractorId = 4,
                            CostPerUnit = 152m,
                            CreatorId = "32f9a0f0-4d62-4573-96e3-fbb7ad7f321f",
                            IsDeleted = false,
                            Quantity = 210.0,
                            SiteId = 1,
                            StageId = 1,
                            TotalCost = 31920m,
                            UnitId = 1,
                            WorkTypeId = 5
                        },
                        new
                        {
                            Id = 11,
                            CarryOutDate = new DateTime(2024, 8, 29, 17, 10, 28, 612, DateTimeKind.Local).AddTicks(9386),
                            ContractorId = 2,
                            CostPerUnit = 135m,
                            CreatorId = "a615552b-5981-4730-be32-12c087492aef",
                            IsDeleted = false,
                            Quantity = 20.0,
                            SiteId = 1,
                            StageId = 1,
                            TotalCost = 2700m,
                            UnitId = 3,
                            WorkTypeId = 6
                        },
                        new
                        {
                            Id = 12,
                            CarryOutDate = new DateTime(2024, 8, 30, 17, 10, 28, 612, DateTimeKind.Local).AddTicks(9390),
                            ContractorId = 5,
                            CostPerUnit = 2.2m,
                            CreatorId = "a615552b-5981-4730-be32-12c087492aef",
                            Description = "Entered cost for reinforcement steel and delivery",
                            IsDeleted = false,
                            Quantity = 57.0,
                            SiteId = 1,
                            StageId = 1,
                            TotalCost = 125.4m,
                            UnitId = 2,
                            WorkTypeId = 7
                        },
                        new
                        {
                            Id = 13,
                            CarryOutDate = new DateTime(2024, 8, 30, 17, 10, 28, 612, DateTimeKind.Local).AddTicks(9394),
                            ContractorId = 1,
                            CostPerUnit = 0.3m,
                            CreatorId = "a615552b-5981-4730-be32-12c087492aef",
                            Description = "Entered cost for reinforcement steel laying",
                            IsDeleted = false,
                            Quantity = 57.0,
                            SiteId = 1,
                            StageId = 1,
                            TotalCost = 17.1m,
                            UnitId = 2,
                            WorkTypeId = 7
                        },
                        new
                        {
                            Id = 14,
                            CarryOutDate = new DateTime(2024, 8, 17, 17, 10, 28, 612, DateTimeKind.Local).AddTicks(9397),
                            ContractorId = 1,
                            CostPerUnit = 8m,
                            CreatorId = "32f9a0f0-4d62-4573-96e3-fbb7ad7f321f",
                            Description = "Entered cost for formwork assembly",
                            IsDeleted = false,
                            Quantity = 57.0,
                            SiteId = 1,
                            StageId = 2,
                            TotalCost = 456m,
                            UnitId = 4,
                            WorkTypeId = 8
                        },
                        new
                        {
                            Id = 15,
                            CarryOutDate = new DateTime(2024, 8, 29, 17, 10, 28, 612, DateTimeKind.Local).AddTicks(9401),
                            ContractorId = 4,
                            CostPerUnit = 8m,
                            CreatorId = "32f9a0f0-4d62-4573-96e3-fbb7ad7f321f",
                            Description = "Used combined excavators",
                            IsDeleted = false,
                            Quantity = 200.0,
                            SiteId = 2,
                            StageId = 1,
                            TotalCost = 1600m,
                            UnitId = 3,
                            WorkTypeId = 3
                        },
                        new
                        {
                            Id = 16,
                            CarryOutDate = new DateTime(2024, 8, 30, 17, 10, 28, 612, DateTimeKind.Local).AddTicks(9404),
                            ContractorId = 4,
                            CostPerUnit = 8m,
                            CreatorId = "32f9a0f0-4d62-4573-96e3-fbb7ad7f321f",
                            IsDeleted = false,
                            Quantity = 100.0,
                            SiteId = 2,
                            StageId = 1,
                            TotalCost = 800m,
                            UnitId = 3,
                            WorkTypeId = 3
                        },
                        new
                        {
                            Id = 17,
                            CarryOutDate = new DateTime(2024, 8, 31, 17, 10, 28, 612, DateTimeKind.Local).AddTicks(9408),
                            ContractorId = 2,
                            CostPerUnit = 450m,
                            CreatorId = "32f9a0f0-4d62-4573-96e3-fbb7ad7f321f",
                            Description = "Entered cost for combined excavator use",
                            IsDeleted = false,
                            Quantity = 2.0,
                            SiteId = 2,
                            StageId = 1,
                            TotalCost = 900m,
                            UnitId = 8,
                            WorkTypeId = 3
                        },
                        new
                        {
                            Id = 18,
                            CarryOutDate = new DateTime(2024, 9, 1, 17, 10, 28, 612, DateTimeKind.Local).AddTicks(9412),
                            ContractorId = 4,
                            CostPerUnit = 164m,
                            CreatorId = "32f9a0f0-4d62-4573-96e3-fbb7ad7f321f",
                            IsDeleted = false,
                            Quantity = 130.0,
                            SiteId = 2,
                            StageId = 1,
                            TotalCost = 21320m,
                            UnitId = 1,
                            WorkTypeId = 4
                        },
                        new
                        {
                            Id = 19,
                            CarryOutDate = new DateTime(2024, 9, 4, 17, 10, 28, 612, DateTimeKind.Local).AddTicks(9415),
                            ContractorId = 4,
                            CostPerUnit = 164m,
                            CreatorId = "32f9a0f0-4d62-4573-96e3-fbb7ad7f321f",
                            IsDeleted = false,
                            Quantity = 250.0,
                            SiteId = 2,
                            StageId = 1,
                            TotalCost = 41000m,
                            UnitId = 1,
                            WorkTypeId = 4
                        },
                        new
                        {
                            Id = 20,
                            CarryOutDate = new DateTime(2024, 9, 3, 17, 10, 28, 612, DateTimeKind.Local).AddTicks(9419),
                            ContractorId = 3,
                            CostPerUnit = 23m,
                            CreatorId = "a615552b-5981-4730-be32-12c087492aef",
                            IsDeleted = false,
                            Quantity = 950.0,
                            SiteId = 3,
                            StageId = 4,
                            TotalCost = 21850m,
                            UnitId = 5,
                            WorkTypeId = 1
                        },
                        new
                        {
                            Id = 21,
                            CarryOutDate = new DateTime(2024, 9, 2, 17, 10, 28, 612, DateTimeKind.Local).AddTicks(9422),
                            ContractorId = 3,
                            CostPerUnit = 23m,
                            CreatorId = "a615552b-5981-4730-be32-12c087492aef",
                            IsDeleted = false,
                            Quantity = 350.0,
                            SiteId = 3,
                            StageId = 4,
                            TotalCost = 8050m,
                            UnitId = 5,
                            WorkTypeId = 1
                        },
                        new
                        {
                            Id = 22,
                            CarryOutDate = new DateTime(2024, 9, 2, 17, 10, 28, 612, DateTimeKind.Local).AddTicks(9425),
                            ContractorId = 4,
                            CostPerUnit = 42.5m,
                            CreatorId = "a615552b-5981-4730-be32-12c087492aef",
                            IsDeleted = false,
                            Quantity = 200.0,
                            SiteId = 3,
                            StageId = 1,
                            TotalCost = 8500m,
                            UnitId = 3,
                            WorkTypeId = 2
                        },
                        new
                        {
                            Id = 23,
                            CarryOutDate = new DateTime(2024, 9, 3, 17, 10, 28, 612, DateTimeKind.Local).AddTicks(9428),
                            ContractorId = 4,
                            CostPerUnit = 42.5m,
                            CreatorId = "a615552b-5981-4730-be32-12c087492aef",
                            IsDeleted = false,
                            Quantity = 390.0,
                            SiteId = 3,
                            StageId = 1,
                            TotalCost = 16575m,
                            UnitId = 3,
                            WorkTypeId = 2
                        });
                });

            modelBuilder.Entity("ConstructionSiteReportingSystem.Infrastructure.Data.Models.WorkType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Construction and assembly work type identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit")
                        .HasComment("Is construction and assembly work type approved by the administrator");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasComment("Construction and assembly work type name");

                    b.HasKey("Id");

                    b.ToTable("WorksTypes");

                    b.HasComment("Construction and assembly work type");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsApproved = true,
                            IsDeleted = false,
                            Name = "PE400 SN8 pipe installation"
                        },
                        new
                        {
                            Id = 2,
                            IsApproved = true,
                            IsDeleted = false,
                            Name = "Delivery,laying and compaction of crushed aggregate for road base"
                        },
                        new
                        {
                            Id = 3,
                            IsApproved = true,
                            IsDeleted = false,
                            Name = "Earthwork excavation"
                        },
                        new
                        {
                            Id = 4,
                            IsApproved = true,
                            IsDeleted = false,
                            Name = "Delivery, laying and compaction of asphalt concrete binder course"
                        },
                        new
                        {
                            Id = 5,
                            IsApproved = true,
                            IsDeleted = false,
                            Name = "Delivery, laying and compaction of asphalt concrete surface course"
                        },
                        new
                        {
                            Id = 6,
                            IsApproved = true,
                            IsDeleted = false,
                            Name = "Delivery and pouring concrete for foundation slab"
                        },
                        new
                        {
                            Id = 7,
                            IsApproved = true,
                            IsDeleted = false,
                            Name = "Delivery and laying of reinforcement steel for foundation slab"
                        },
                        new
                        {
                            Id = 8,
                            IsApproved = true,
                            IsDeleted = false,
                            Name = "Large-area formwork for concrete slab"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClaimType = "user:firstlastname",
                            ClaimValue = "Konstantin Kirilov",
                            UserId = "32f9a0f0-4d62-4573-96e3-fbb7ad7f321f"
                        },
                        new
                        {
                            Id = 2,
                            ClaimType = "user:firstlastname",
                            ClaimValue = "Ivan Metodiev",
                            UserId = "a615552b-5981-4730-be32-12c087492aef"
                        },
                        new
                        {
                            Id = 3,
                            ClaimType = "user:firstlastname",
                            ClaimValue = "Anton Kovadzhiev",
                            UserId = "51d6e97b-9c12-4832-95e1-c0dfa1715ad9"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ConstructionSiteReportingSystem.Infrastructure.Data.Models.Task", b =>
                {
                    b.HasOne("ConstructionSiteReportingSystem.Infrastructure.Data.Models.ApplicationUser", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("ConstructionSiteReportingSystem.Infrastructure.Data.Models.Work", b =>
                {
                    b.HasOne("ConstructionSiteReportingSystem.Infrastructure.Data.Models.Contractor", "Contractor")
                        .WithMany("Works")
                        .HasForeignKey("ContractorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ConstructionSiteReportingSystem.Infrastructure.Data.Models.ApplicationUser", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConstructionSiteReportingSystem.Infrastructure.Data.Models.Site", "Site")
                        .WithMany("Works")
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ConstructionSiteReportingSystem.Infrastructure.Data.Models.Stage", "Stage")
                        .WithMany("Works")
                        .HasForeignKey("StageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ConstructionSiteReportingSystem.Infrastructure.Data.Models.Unit", "Unit")
                        .WithMany("Works")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ConstructionSiteReportingSystem.Infrastructure.Data.Models.WorkType", "WorkType")
                        .WithMany("Works")
                        .HasForeignKey("WorkTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Contractor");

                    b.Navigation("Creator");

                    b.Navigation("Site");

                    b.Navigation("Stage");

                    b.Navigation("Unit");

                    b.Navigation("WorkType");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ConstructionSiteReportingSystem.Infrastructure.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ConstructionSiteReportingSystem.Infrastructure.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConstructionSiteReportingSystem.Infrastructure.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ConstructionSiteReportingSystem.Infrastructure.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ConstructionSiteReportingSystem.Infrastructure.Data.Models.Contractor", b =>
                {
                    b.Navigation("Works");
                });

            modelBuilder.Entity("ConstructionSiteReportingSystem.Infrastructure.Data.Models.Site", b =>
                {
                    b.Navigation("Works");
                });

            modelBuilder.Entity("ConstructionSiteReportingSystem.Infrastructure.Data.Models.Stage", b =>
                {
                    b.Navigation("Works");
                });

            modelBuilder.Entity("ConstructionSiteReportingSystem.Infrastructure.Data.Models.Unit", b =>
                {
                    b.Navigation("Works");
                });

            modelBuilder.Entity("ConstructionSiteReportingSystem.Infrastructure.Data.Models.WorkType", b =>
                {
                    b.Navigation("Works");
                });
#pragma warning restore 612, 618
        }
    }
}
